In [1]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
# enhance Python's capabilities for numerical operations?

# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
# other?

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
# arrays.

# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance.

# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.

# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.

# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?

# Practical Questions:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.

# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [2]:
# 1. Purpose and Advantages of NumPy in Scientific Computing and Data Analysis
''' NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing and data analysis due to several advantages:

Performance: NumPy arrays (ndarrays) are optimized for performance, especially for large-scale numerical computations, as they are implemented in C and Fortran, leading to faster execution.
Memory Efficiency: NumPy arrays are more memory-efficient than Python lists since they store elements in a contiguous block of memory, allowing for faster access and operations.
Vectorized Operations: NumPy allows for element-wise operations on arrays without the need for explicit loops, leading to cleaner and more concise code.
Broad Functionality: NumPy offers a wide range of mathematical, statistical, and linear algebra functions, making it essential for data analysis, scientific computing, and machine learning.
Integration: NumPy can interface with other libraries like pandas, SciPy, and TensorFlow, making it a foundation for many scientific and data analysis tools.'''

' NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is widely used in scientific computing and data analysis due to several advantages:\n\nPerformance: NumPy arrays (ndarrays) are optimized for performance, especially for large-scale numerical computations, as they are implemented in C and Fortran, leading to faster execution.\nMemory Efficiency: NumPy arrays are more memory-efficient than Python lists since they store elements in a contiguous block of memory, allowing for faster access and operations.\nVectorized Operations: NumPy allows for element-wise operations on arrays without the need for explicit loops, leading to cleaner and more concise code.\nBroad Functionality: NumPy offers a wide range of mathematical, statistical, and linear algebra functions, making it essential for data analysis, scientific computing, and machine learning

In [3]:
# 2. Comparison of np.mean() and np.average()
'''np.mean(): This function calculates the arithmetic mean (average) of the elements along a given axis or for the entire array.'''
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5


2.5


In [6]:
# np.average(): While it also computes the mean, it allows for specifying weights for each element, which can be useful for weighted averages.
weights = np.array([1,2,3,4]) 
print(np.average(weights))

# When to use: Use np.mean() for standard arithmetic means, and np.average() when you need a weighted average. If no weights are provided, np.average() behaves like np.mean().

2.5


In [8]:
# 3. Reversing a NumPy Array
# To reverse a NumPy array, you can use slicing or specific functions for different axes.
# Here's how you can do it:
arr = np.array([22,43,5,6,5])
reversed_array = arr[::-1]
reversed_array

array([ 5,  6,  5, 43, 22])

In [16]:
# For a 2D array along different axes:
arr_2d = np.array([[1,2],[2,3]])
reversed_arr = arr_2d[::-1, :]
reversed_arr

array([[2, 3],
       [1, 2]])

In [19]:
# To reverse along columns:
reversed_cols = arr_2d[:,::-1]
print(reversed_cols)  # Output: [[2 1], [4 3]]


[[2 1]
 [3 2]]


In [20]:
# 4. Determining the Data Type of Elements in a NumPy Array
# You can determine the data type of elements in a NumPy array using the dtype attribute.
arr = np.array([1,2,3,4,55])
arr.dtype

dtype('int32')

In [21]:
arr = np.array([1,2,3,4,55], dtype=np.float32)
arr.dtype

dtype('float32')

In [22]:
# Importance of Data Types: Data types play a crucial role in memory management and performance. For example, using float64 requires more memory than float32, and using the wrong data type can lead to slower performance or overflow errors.

In [23]:
# 5. Defining ndarray and Key Features
# An ndarray (n-dimensional array) is the core data structure of NumPy. Its key features include:

# Homogeneous Data: All elements have the same data type, unlike Python lists which can hold mixed types.
# N-Dimensional: It supports multi-dimensional arrays (1D, 2D, 3D, etc.).
# Efficient Memory Layout: Elements are stored in contiguous memory blocks, making access and manipulation faster.
# Broadcasting: Supports operations on arrays of different shapes.
# Vectorization: Enables element-wise operations without loops. 
# Compared to Python lists, ndarray is more memory-efficient and faster, especially for numerical computations

In [24]:
# 6. Performance Benefits of NumPy Arrays over Python Lists
# NumPy arrays offer significant performance advantages over Python lists for large-scale numerical operations:

# Memory Efficiency: NumPy arrays are more compact because they store data in a contiguous block of memory, while Python lists store pointers to objects.
# Speed: Operations on NumPy arrays are faster because they are implemented in low-level languages like C.
# Vectorized Operations: NumPy performs operations in a vectorized way, avoiding the overhead of Python loops.

import time

arr = np.arange(1000000)
list_arr = list(range(1000000))

start_time = time.time()
arr * 2
print("NumPy array operation:", time.time() - start_time)

start_time = time.time()
[el * 2 for el in list_arr]
print("Python list operation:", time.time() - start_time)


NumPy array operation: 0.004983663558959961
Python list operation: 0.16275858879089355


In [25]:
# 7. Comparison of vstack() and hstack()

# vstack(): Vertically stacks arrays (along the first axis).
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.vstack((arr1, arr2))) 


[[1 2]
 [3 4]]


In [26]:
# hstack(): Horizontally stacks arrays (along the second axis).
print(np.hstack((arr1, arr2)))

[1 2 3 4]


In [27]:
# 8. Differences between fliplr() and flipud()
# fliplr(): Flips an array along its left-right (horizontal) axis.

arr = np.array([[1, 2], [3, 4]])
print(np.fliplr(arr)) 

[[2 1]
 [4 3]]


In [28]:
# flipud(): Flips an array along its up-down (vertical) axis.


print(np.flipud(arr)) 

[[3 4]
 [1 2]]


In [29]:
# 9. Functionality of array_split()
# The array_split() method splits an array into sub-arrays. It can handle uneven splits by allowing the last sub-array to have fewer elements.
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))


[array([1, 2]), array([3, 4]), array([5])]


In [30]:
# 10. Vectorization and Broadcasting in NumPy
# Vectorization: The process of performing operations on entire arrays at once without loops. This leads to more concise and faster code.
arr = np.array([1, 2, 3])
print(arr * 2)  



[2 4 6]


In [31]:
# Broadcasting: Allows NumPy to perform operations on arrays of different shapes by stretching the smaller array across the larger one
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
print(arr1 + arr2) 


[[2 4 6]
 [5 7 9]]


# Practical Questions


In [33]:
#1. Creating a 3X3 Numpy array
arr = np.random.randint(1,101, size = (3,3))
arr

array([[63, 12, 76],
       [44,  8,  3],
       [77, 90, 22]])

In [34]:
#Inter changing the rows and cols
arr.T

array([[63, 44, 77],
       [12,  8, 90],
       [76,  3, 22]])

In [37]:
# 2.Generating a 1d Numpy array with 10 elements
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#Resahping array in 2x5 array
arr_2x5 = arr.reshape(2,5)
arr_2x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
#Reshaping in 5x2 array
arr_5x2 = arr.reshape(5,2)

In [42]:
#3 creating a 4x4 array with random float values
arr = np.random.rand(4,4)
arr



array([[0.3940252 , 0.28008607, 0.35786618, 0.42747364],
       [0.22137132, 0.02307408, 0.87457688, 0.28971151],
       [0.86127291, 0.26112224, 0.26976939, 0.85211049],
       [0.32173204, 0.84743511, 0.42490133, 0.31379436]])

In [43]:
#Add a border of zeros around the array
arr_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr_border

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.3940252 , 0.28008607, 0.35786618, 0.42747364,
        0.        ],
       [0.        , 0.22137132, 0.02307408, 0.87457688, 0.28971151,
        0.        ],
       [0.        , 0.86127291, 0.26112224, 0.26976939, 0.85211049,
        0.        ],
       [0.        , 0.32173204, 0.84743511, 0.42490133, 0.31379436,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [46]:
#4. 
arr = np.random.randint(10,65, 5)
arr

array([35, 16, 64, 55, 28])

In [47]:
# 5. Creating an array of string['python','numpy',pandas,]
array = np.array(['python','numpy','pandas']) 
array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [49]:
#Upper case
print("Upper case: ", np.char.upper(array))

#lowercase
print("Lower case: ", np.char.lower(array))

#Title case
print("Title case: ", np.char.title(array))



Upper case:  ['PYTHON' 'NUMPY' 'PANDAS']
Lower case:  ['python' 'numpy' 'pandas']
Title case:  ['Python' 'Numpy' 'Pandas']


In [50]:
#6. Inserting a space betweem each character of every word
spaced_arr = np.char.join(" ", array)
print(spaced_arr)  

['p y t h o n' 'n u m p y' 'p a n d a s']


In [51]:
#7. element wise operation on 2d arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[2,2],[4,4]])

# Element-wise addition
add_result = arr1 + arr2

# Element-wise subtraction
sub_result = arr1 - arr2

# Element-wise multiplication
mul_result = arr1 * arr2

# Element-wise division
div_result = arr1 / arr2

print("Addition Result:\n", add_result)
print("Subtraction Result:\n", sub_result)
print("Multiplication Result:\n", mul_result)
print("Division Result:\n", div_result)

Addition Result:
 [[3 4]
 [7 8]]
Subtraction Result:
 [[-1  0]
 [-1  0]]
Multiplication Result:
 [[ 2  4]
 [12 16]]
Division Result:
 [[0.5  1.  ]
 [0.75 1.  ]]


In [52]:
#8. Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

#Extract the diagonal element
diagonal_element = np.diag(identity_matrix)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
print(diagonal_element)

[1. 1. 1. 1. 1.]


In [59]:
#9. Generating an array of 100 random intigers between 0 an 1000
import sympy
arr = np.random.randint(0, 1000, 100)

#Check for prime numbers
prime = np.array([num for num in arr if sympy.isprime(num)])

print("Array of Random Intigets : ", arr)

print("\nPrime Numbers in the Array : ", prime)

Array of Random Intigets :  [433 520 343  57 483 769 970  52 339 890 433 671 196  89  84 773 370 369
 673  75 946 460  97 354 210 838 187 844 811 172 798 187 486 865 310 446
 429 924 476 173 358 782 971 676 160 972 604 857 892 969 569 515 443 594
 794 997 859 598 308 584  51 372 820 398 204 324 494 372 792 811  63 211
 241 426  31 423 606 714 841 846 394 205 380 512 604 384 149 254 420  97
 385 879 557 214 937 381 793 438 981 895]

Prime Numbers in the Array :  [433 769 433  89 773 673  97 811 173 971 857 569 443 997 859 811 211 241
  31 149  97 557 937]


In [66]:
#10. Calculate weakly average of daily tempratures of a month

#generate an array of daily temp for 30 days
daily_temp = np.random.randint(60, 100,28) #Random temp between 50 degreee F to 100 F

#reshaping the array to 4 weeks
weekly_tmp = daily_temp[:28].reshape(4,7)

#Calaculating the weakly average
weekly_avg = np.mean(weekly_tmp, axis=1)

print("Daily temp for 4 weeks : ", weekly_tmp)
print("\nWeekly average :", weekly_avg)

Daily temp for 4 weeks :  [[74 97 87 74 81 97 92]
 [93 73 70 98 79 87 93]
 [92 67 90 75 72 70 71]
 [63 68 83 65 62 72 75]]

Weekly average : [86.         84.71428571 76.71428571 69.71428571]
